# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb68157a726edbda28726780222acaffbe195896551c349b002f6c0b98d484cdb296f03b325fdc62a5a4f9e1eb9390e6b329f27ce52017e5c6ab98c277e8cf29

test:
  secret_key_base: 105a2b98cb1e42c67bb4bd8a63a20a019863c138b3870ed69f7fd0d07b7e4483c8f54c97cd489033eb3660f13a66bcc223772653568a5ff02f91d0f78d8c2e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
